#! /bin/bash
#python setup.py --command-packages=stdeb.command sdist_dsc debianize bdist_deb
#./cleanall
#dh_make --createorig -s -c gpl -a -e freetogo@gmail.com
export DEBEMAIL=${LOGNAME}@nowhere.com
export DEBFULLNAME=${USERNAME}
export CFLAGS='-g -O3'
rootDir=${PWD}
pkgName=${PWD##*/}
baseDir=deb_dist/${pkgName}
rm deb_dist -Rf
rm debian/source -Rf
dch --nmu
#debuild -us -uc
#debuild -b
#DEB_CPPFLAGS_SET="-I/foo/bar/baz" DEB_CFLAGS_SET="-g -O6" DEB_LDFLAGS_SET="-L/fruzzel/frazzel/" dpkg-buildpackage -uc -us -j8 -rfakeroot
DEB_CFLAGS_SET="-g -O3" dpkg-buildpackage -uc -us -j8 -rfakeroot
