#!/bin/bash
#PREFIX=x86_64-w64-mingw32
WORKDIR=$(readlink -f ~/mingw64)
MXE="/opt/mxe"
CROSS=x86_64-w64-mingw32
HOST=$CROSS
TARGET=$CROSS.shared

#PREFIX=$WORKDIR/$TARGET
MXE_BIN=$MXE/usr/bin
DESTDIR=/opt/mxe
PREFIX=$DESTDIR/usr/$TARGET
EPREFIX=PREFIX


CC=$TARGET-gcc
CXX=$TARGET-g++
CPP=$TARGET-cpp
RANLIB=$TARGET-ranlib
LD=$TARGET-ld
AR=$TARGET-ar
PKG_CONFIG=$TARGET-pkg-config
PATH=$MXE_BIN:$PATH
#PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig:$PKG_CONFIG_PATH
if [[ $1 == *configure* ]]
then 
	exec "$@" --host=$TARGET --prefix=$PREFIX 
else
	exec "$@"
fi
print $1

